---
deployment:
  tasks:
    - export DEPLOYPATH=/home/heinrozl/public_html
    - /bin cp/views/ * $DEPLOYPATH
    - /bin/cp mail.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin cp/assets/ * $DEPLOYPATH